// Curated realistic products across all categories and subcategories
const additionalProducts = [
  // ==========================================
  // 1. MOBILES (Parent ID: 1)
  // ==========================================
  // Feature Phones (102)
  {
    categoryId: 1,
    subcategoryId: 102,
    brand: 'Nokia',
    name: 'Nokia 3310 4G Feature Phone with VoLTE & Long Battery',
    slug: 'nokia-3310-4g-warm-red',
    description: 'Iconic durable keypad phone featuring 4G VoLTE calling, FM radio, MP3 player, classic Snake game and up to 12 days standby time.',
    price: 3499,
    mrp: 4299,
    rating: 4.4,
    reviewCount: 3200,
    stock: 50,
    sku: 'NOK-3310-4G',
    thumbnail: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80',
    badge: 'Classic Favorite',
    specs: { Model: '3310 4G', Display: '2.4 inch QVGA', Battery: '1200 mAh', Connectivity: '4G VoLTE, Bluetooth', Storage: 'Up to 32GB expandable' }
  },
  {
    categoryId: 1,
    subcategoryId: 102,
    brand: 'Nokia',
    name: 'Nokia 105 All-New Single SIM Keypad Phone',
    slug: 'nokia-105-keypad-black',
    description: 'Ultra-reliable compact keypad phone with crystal clear call quality, wireless FM radio, built-in flashlight and ergonomic curved body.',
    price: 1399,
    mrp: 1799,
    rating: 4.3,
    reviewCount: 8400,
    stock: 80,
    sku: 'NOK-105-BLK',
    thumbnail: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=600&q=80',
    specs: { Model: '105', Display: '1.8 inch QQVGA', Battery: '1000 mAh', Feature: 'Built-in Torch' }
  },
  {
    categoryId: 1,
    subcategoryId: 102,
    brand: 'Samsung',
    name: 'Samsung Guru Music 2 Dual SIM Keypad Phone',
    slug: 'samsung-guru-music-2-gold',
    description: 'Enhanced loudspeaker stereo music phone with dual SIM standby, 16GB expandable micro SD slot, FM recording and 11 hours talk time.',
    price: 2199,
    mrp: 2699,
    rating: 4.5,
    reviewCount: 12400,
    stock: 65,
    sku: 'SAM-GURU-M2',
    thumbnail: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80',
    specs: { Model: 'Guru Music 2', Display: '2.0 inch TFT', Battery: '800 mAh', Audio: 'Dedicated MP3 & Stereo Speaker' }
  },

  // Chargers (105)
  {
    categoryId: 1,
    subcategoryId: 105,
    brand: 'Apple',
    name: 'Apple 20W USB-C Power Adapter for iPhone & iPad',
    slug: 'apple-20w-usb-c-power-adapter',
    description: 'Original Apple 20W USB-C compact power brick offering high-speed fast charging from 0% to 50% in 30 minutes for iPhone 16 / 15 / 14 / 13 series.',
    price: 1699,
    mrp: 1900,
    rating: 4.7,
    reviewCount: 15400,
    stock: 100,
    sku: 'APL-20W-ADPT',
    thumbnail: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    badge: 'Apple Official',
    specs: { Wattage: '20 Watts', Port: 'USB Type-C', Compatibility: 'iPhone, iPad, AirPods', Warranty: '1 Year Official Apple Warranty' }
  },
  {
    categoryId: 1,
    subcategoryId: 105,
    brand: 'Anker',
    name: 'Anker 737 GaNPrime 120W 3-Port Fast Wall Charger',
    slug: 'anker-737-120w-gan-charger',
    description: 'Flagship GaNPrime 120W multi-device fast charger with Dynamic Power Distribution, 2x USB-C + 1x USB-A ports. Powers MacBook Pro, iPhone, and Galaxy simultaneously.',
    price: 6499,
    mrp: 8999,
    rating: 4.8,
    reviewCount: 2100,
    stock: 40,
    sku: 'ANK-737-120W',
    thumbnail: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    badge: 'GaN Tech',
    specs: { Output: '120W Max', Ports: '2 USB-C + 1 USB-A', Technology: 'GaNPrime & ActiveShield 2.0', Weight: '187g' }
  },

  // Power Banks (106)
  {
    categoryId: 1,
    subcategoryId: 106,
    brand: 'Xiaomi',
    name: 'Mi 20000mAh 33W Fast Charging Power Bank Pocket Pro',
    slug: 'mi-20000mah-33w-power-bank',
    description: 'Triple port output power bank with Type-C two-way 33W sonic charge, high-density lithium polymer battery cells and 12-layer advanced circuit protection.',
    price: 2199,
    mrp: 2999,
    rating: 4.5,
    reviewCount: 8800,
    stock: 60,
    sku: 'MI-PB-20K-33W',
    thumbnail: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '20,000 mAh', MaxOutput: '33 Watts Fast Charge', Ports: '2 USB-A + 1 USB-C', Battery: 'Lithium Polymer' }
  },
  {
    categoryId: 1,
    subcategoryId: 106,
    brand: 'Anker',
    name: 'Anker 737 Power Bank (PowerCore 24K) 140W Portable Charger',
    slug: 'anker-737-powercore-24k-140w',
    description: 'Elite 24000mAh portable charger equipped with smart digital display, Power Delivery 3.1 and bi-directional 140W ultra-fast charging to power laptops on the go.',
    price: 11999,
    mrp: 14999,
    rating: 4.9,
    reviewCount: 1600,
    stock: 25,
    sku: 'ANK-PC-24K-140W',
    thumbnail: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=600&q=80',
    badge: '140W Output',
    specs: { Capacity: '24,000 mAh', Output: '140W Bi-directional', Screen: 'Smart Color Digital Display', Weight: '630g' }
  },

  // Cases & Screen Protectors (104, 107)
  {
    categoryId: 1,
    subcategoryId: 104,
    brand: 'Apple',
    name: 'Apple iPhone 16 Pro Silicone Case with MagSafe',
    slug: 'apple-iphone-16-pro-silicone-case-black',
    description: 'Silky, soft-touch silicone exterior with built-in magnets that align perfectly with iPhone 16 Pro for effortless wireless charging and Camera Control button support.',
    price: 4900,
    mrp: 4900,
    rating: 4.6,
    reviewCount: 1450,
    stock: 75,
    sku: 'APL-IP16P-CS-BLK',
    thumbnail: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=600&q=80',
    specs: { Material: 'Premium Liquid Silicone', MagSafe: 'Yes, Full Magnetic Ring', Compatibility: 'iPhone 16 Pro' }
  },

  // ==========================================
  // 2. ELECTRONICS (Parent ID: 2)
  // ==========================================
  // Monitors (210)
  {
    categoryId: 2,
    subcategoryId: 210,
    brand: 'LG',
    name: 'LG 27-inch 4K UHD IPS Monitor with HDR10 & USB-C 90W',
    slug: 'lg-27-inch-4k-uhd-monitor-27up850',
    description: 'Vibrant 4K UHD (3840x2160) IPS panel with 99% sRGB, VESA DisplayHDR 400, AMD FreeSync, built-in MaxxAudio speakers and 90W USB Type-C laptop docking.',
    price: 32999,
    mrp: 45000,
    rating: 4.6,
    reviewCount: 1800,
    stock: 20,
    sku: 'LG-27UP850-4K',
    thumbnail: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
    badge: '4K Creator Choice',
    specs: { ScreenSize: '27 Inch', Resolution: '3840 x 2160 (4K UHD)', Panel: 'IPS Anti-Glare', RefreshRate: '60Hz', Ports: 'USB-C 90W, HDMI 2.0, DP 1.4' }
  },
  {
    categoryId: 2,
    subcategoryId: 210,
    brand: 'Samsung',
    name: 'Samsung Odyssey G7 32-inch QHD Curved 240Hz Gaming Monitor',
    slug: 'samsung-odyssey-g7-32-inch-240hz',
    description: '1000R curved gaming beast featuring QLED Quantum Dot colors, 240Hz ultra-smooth refresh rate, 1ms response time, G-Sync compatible and HDR600.',
    price: 46999,
    mrp: 62000,
    rating: 4.7,
    reviewCount: 1400,
    stock: 15,
    sku: 'SAM-ODYS-G7-32',
    thumbnail: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
    badge: '240Hz 1ms',
    specs: { ScreenSize: '32 Inch Curved (1000R)', Resolution: '2560 x 1440 (QHD)', RefreshRate: '240Hz', ResponseTime: '1ms (GtG)' }
  },
  {
    categoryId: 2,
    subcategoryId: 210,
    brand: 'Dell',
    name: 'Dell UltraSharp 27 4K USB-C Hub Monitor (U2723QE)',
    slug: 'dell-ultrasharp-27-4k-u2723qe',
    description: 'World-renowned IPS Black technology monitor delivering 2000:1 contrast ratio, 100% sRGB, 98% DCI-P3, RJ45 Ethernet port and 90W power delivery.',
    price: 54990,
    mrp: 72000,
    rating: 4.8,
    reviewCount: 950,
    stock: 18,
    sku: 'DELL-U2723QE',
    thumbnail: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
    specs: { ScreenSize: '27 Inch', Technology: 'IPS Black (2000:1 Contrast)', ColorGamut: '98% DCI-P3', Connectivity: 'USB-C Hub, RJ45 LAN, DisplayPort' }
  },

  // Printers (211)
  {
    categoryId: 2,
    subcategoryId: 211,
    brand: 'HP',
    name: 'HP Smart Tank 580 All-in-One Color WiFi Ink Tank Printer',
    slug: 'hp-smart-tank-580-wifi-printer',
    description: 'Cost-effective high-volume wireless color printing, scanning and copying. Up to 12,000 black and 6,000 color pages included in the box with 10 paise per page print cost.',
    price: 13999,
    mrp: 18450,
    rating: 4.4,
    reviewCount: 3100,
    stock: 25,
    sku: 'HP-ST580-PRN',
    thumbnail: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=600&q=80',
    specs: { Type: 'Color Ink Tank All-in-One', Functions: 'Print, Scan, Copy', Connectivity: 'Wi-Fi, Bluetooth, USB', PageYield: '12000 Black / 6000 Color' }
  },
  {
    categoryId: 2,
    subcategoryId: 211,
    brand: 'Canon',
    name: 'Canon PIXMA MegaTank G3010 All-in-One Wireless Ink Tank',
    slug: 'canon-pixma-g3010-printer',
    description: 'High page-yield color ink tank printer with integrated transparent ink tanks, borderless photo printing and seamless mobile printing via Canon PRINT app.',
    price: 12499,
    mrp: 16995,
    rating: 4.3,
    reviewCount: 4200,
    stock: 30,
    sku: 'CAN-G3010-PRN',
    thumbnail: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=600&q=80',
    specs: { Type: 'Ink Tank Multifunction', Resolution: '4800 x 1200 dpi', Speed: '8.8 ipm Black / 5.0 ipm Color' }
  },

  // Storage Devices (212)
  {
    categoryId: 2,
    subcategoryId: 212,
    brand: 'Samsung',
    name: 'Samsung 990 PRO 2TB PCIe 4.0 NVMe M.2 Internal SSD',
    slug: 'samsung-990-pro-2tb-nvme-ssd',
    description: 'Blistering fast PCIe Gen 4.0 read speeds up to 7,450 MB/s and write speeds up to 6,900 MB/s. Built for hardcore gaming, 4K/8K video editing and PS5 consoles.',
    price: 18999,
    mrp: 26999,
    rating: 4.9,
    reviewCount: 2800,
    stock: 45,
    sku: 'SAM-990PRO-2TB',
    thumbnail: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
    badge: '7,450 MB/s',
    specs: { Capacity: '2TB', Interface: 'PCIe 4.0 x4, NVMe 2.0', FormFactor: 'M.2 2280', ReadSpeed: '7,450 MB/s', Endurance: '1200 TBW' }
  },
  {
    categoryId: 2,
    subcategoryId: 212,
    brand: 'SanDisk',
    name: 'SanDisk Extreme 1TB Portable External NVMe SSD',
    slug: 'sandisk-extreme-1tb-portable-ssd',
    description: 'Tough, pocket-sized external drive with 1050MB/s transfer speeds, IP55 water and dust resistance, 2-meter drop protection and handy carabiner loop.',
    price: 8999,
    mrp: 14500,
    rating: 4.7,
    reviewCount: 7100,
    stock: 55,
    sku: 'SND-EXTR-1TB',
    thumbnail: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '1TB', ReadSpeed: '1050 MB/s', Durability: 'IP55 Water & Dust Resistant', Interface: 'USB 3.2 Gen 2 Type-C' }
  },

  // ==========================================
  // 3. FASHION (Parent ID: 3)
  // ==========================================
  // Men's Clothing (301)
  {
    categoryId: 3,
    subcategoryId: 301,
    brand: "Levi's",
    name: "Levi's Men's 511 Slim Fit Stretch Denim Jeans",
    slug: 'levis-511-slim-fit-stretch-jeans',
    description: 'Timeless modern slim-cut jeans crafted from premium stretch cotton denim with a lean look through the thigh and straight leg opening.',
    price: 2499,
    mrp: 4199,
    rating: 4.5,
    reviewCount: 4800,
    stock: 60,
    sku: 'LEV-511-SLIM',
    thumbnail: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80',
    badge: 'Bestselling Denim',
    specs: { Fit: 'Slim Fit', Material: '99% Cotton, 1% Elastane', Rise: 'Mid Rise', Closure: 'Zip Fly with Button' },
    variants: [
      { name: 'Waist Size', value: '30', price: 2499 },
      { name: 'Waist Size', value: '32', price: 2499 },
      { name: 'Waist Size', value: '34', price: 2499 },
      { name: 'Waist Size', value: '36', price: 2499 }
    ]
  },
  {
    categoryId: 3,
    subcategoryId: 301,
    brand: 'Peter England',
    name: 'Peter England Men Regular Fit Pure Cotton Formal Shirt',
    slug: 'peter-england-formal-cotton-shirt-white',
    description: 'Crisp white formal work shirt made of breathable 100% combed cotton, semi-cutaway spread collar, single chest pocket and wrinkle-resistant finish.',
    price: 1199,
    mrp: 1799,
    rating: 4.4,
    reviewCount: 3200,
    stock: 45,
    sku: 'PE-SHT-WHT-REG',
    thumbnail: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
    specs: { Fabric: '100% Cotton', Collar: 'Spread Collar', Pattern: 'Solid White', Sleeve: 'Full Sleeve' },
    variants: [
      { name: 'Collar Size', value: '39 (M)', price: 1199 },
      { name: 'Collar Size', value: '40 (L)', price: 1199 },
      { name: 'Collar Size', value: '42 (XL)', price: 1199 }
    ]
  },

  // Women's Clothing (302)
  {
    categoryId: 3,
    subcategoryId: 302,
    brand: 'Zara',
    name: 'Zara Floral Print Midi Dress with Belt',
    slug: 'zara-floral-print-midi-dress',
    description: 'Elegant flowy midi dress with a V-neckline, puff sleeves, matching fabric belt with buckle and concealed side zip closure. Perfect for brunches and semi-formal evenings.',
    price: 3590,
    mrp: 4990,
    rating: 4.6,
    reviewCount: 920,
    stock: 30,
    sku: 'ZAR-DRS-FLR-01',
    thumbnail: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80',
    specs: { Length: 'Midi', Material: '100% Viscose', Neck: 'V-Neck', Care: 'Machine Wash Delicate' },
    variants: [
      { name: 'Size', value: 'XS', price: 3590 },
      { name: 'Size', value: 'S', price: 3590 },
      { name: 'Size', value: 'M', price: 3590 },
      { name: 'Size', value: 'L', price: 3590 }
    ]
  },
  {
    categoryId: 3,
    subcategoryId: 302,
    brand: 'H&M',
    name: 'H&M Relaxed Fit Linen Blend Shirt',
    slug: 'hm-relaxed-fit-linen-shirt',
    description: 'Airy linen-blend shirt featuring a turn-down collar, French front buttons, dropped shoulders and an open chest patch pocket.',
    price: 1999,
    mrp: 2499,
    rating: 4.5,
    reviewCount: 1800,
    stock: 40,
    sku: 'HM-LIN-SHT-BEI',
    thumbnail: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80',
    specs: { Composition: '55% Linen, 45% Cotton', Fit: 'Relaxed Oversized', Style: 'Summer Resort' },
    variants: [
      { name: 'Size', value: 'S', price: 1999 },
      { name: 'Size', value: 'M', price: 1999 },
      { name: 'Size', value: 'L', price: 1999 }
    ]
  },

  // Shoes & Sneakers (304, 305)
  {
    categoryId: 3,
    subcategoryId: 305,
    brand: 'Nike',
    name: 'Nike Air Max 270 Men Casual Running Sneakers',
    slug: 'nike-air-max-270-black-white',
    description: "Nike's biggest heel Air unit provides super-soft cushioning that feels as impossible as it looks, enveloped in a breathable engineered mesh upper.",
    price: 11495,
    mrp: 13995,
    rating: 4.8,
    reviewCount: 6500,
    stock: 35,
    sku: 'NKE-AM270-BW',
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    badge: 'Iconic Air',
    specs: { Cushioning: 'Max Air 270 Heel Unit', Upper: 'Engineered Woven Mesh', Sole: 'Rubber Traction Outsole', Gender: "Men" },
    variants: [
      { name: 'Shoe Size (UK)', value: 'UK 7', price: 11495 },
      { name: 'Shoe Size (UK)', value: 'UK 8', price: 11495 },
      { name: 'Shoe Size (UK)', value: 'UK 9', price: 11495 },
      { name: 'Shoe Size (UK)', value: 'UK 10', price: 11495 }
    ]
  },
  {
    categoryId: 3,
    subcategoryId: 305,
    brand: 'Adidas',
    name: 'Adidas Ultraboost Light Running Shoes',
    slug: 'adidas-ultraboost-light-core-black',
    description: 'Experience epic energy return with Light BOOST, featuring an engineered PRIMEKNIT+ textile upper and Continental Better Rubber grip.',
    price: 13999,
    mrp: 18999,
    rating: 4.9,
    reviewCount: 4100,
    stock: 25,
    sku: 'ADI-UB-LGT-BLK',
    thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
    badge: 'Light Boost Tech',
    specs: { Midsole: 'Light BOOST Energy Foam', Drop: '10 mm', Weight: '299g (Size UK 8.5)' },
    variants: [
      { name: 'Shoe Size (UK)', value: 'UK 8', price: 13999 },
      { name: 'Shoe Size (UK)', value: 'UK 9', price: 13999 },
      { name: 'Shoe Size (UK)', value: 'UK 10', price: 13999 }
    ]
  },
  {
    categoryId: 3,
    subcategoryId: 304,
    brand: 'Puma',
    name: 'Puma Smash v2 Leather Unisex Sneakers',
    slug: 'puma-smash-v2-white-black',
    description: 'Tennis-inspired everyday sneaker with soft genuine leather upper, SoftFoam+ comfort sockliner and non-marking durable rubber sole.',
    price: 2799,
    mrp: 4499,
    rating: 4.4,
    reviewCount: 9300,
    stock: 70,
    sku: 'PUM-SMASH-V2',
    thumbnail: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=600&q=80',
    specs: { Material: 'Leather Upper', Insole: 'SoftFoam+ Cushioning', Closure: 'Lace-Up' },
    variants: [
      { name: 'Size', value: 'UK 7', price: 2799 },
      { name: 'Size', value: 'UK 8', price: 2799 },
      { name: 'Size', value: 'UK 9', price: 2799 }
    ]
  },
  {
    categoryId: 3,
    subcategoryId: 304,
    brand: 'Woodland',
    name: "Woodland Men's Camel Leather Casual Trekking Boots",
    slug: 'woodland-camel-leather-trekking-boots',
    description: 'Rugged outdoor leather boots built from nubuck full-grain leather, deep grooved rubber lugs for anti-slip grip and cushioned collar.',
    price: 4395,
    mrp: 5995,
    rating: 4.6,
    reviewCount: 3800,
    stock: 40,
    sku: 'WDL-BOOT-CAMEL',
    thumbnail: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=600&q=80',
    badge: 'Genuine Leather',
    specs: { Material: 'Nubuck Oil Pull-Up Leather', Sole: 'Thermoplastic Rubber (TPR)', Style: 'High-Ankle Trekking' }
  },
  {
    categoryId: 3,
    subcategoryId: 304,
    brand: 'Bata',
    name: "Bata Men's Formal Derby Black Leather Shoes",
    slug: 'bata-mens-formal-derby-black',
    description: 'Sleek executive lace-up dress shoes made with fine polished leather, padded footbed and flexible slip-resistant sole.',
    price: 1899,
    mrp: 2499,
    rating: 4.3,
    reviewCount: 5200,
    stock: 50,
    sku: 'BAT-DRB-BLK-01',
    thumbnail: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=600&q=80',
    specs: { Upper: 'Genuine Leather', Lining: 'Breathable Synthetic', Sole: 'PU Lightweight' }
  },

  // ==========================================
  // 4. APPLIANCES (Parent ID: 4)
  // ==========================================
  // Refrigerators (401)
  {
    categoryId: 4,
    subcategoryId: 401,
    brand: 'LG',
    name: 'LG 242L 3-Star Smart Inverter Double Door Refrigerator',
    slug: 'lg-242l-3-star-smart-inverter-refrigerator',
    description: 'Frost-free double door refrigerator featuring Smart Inverter Compressor, Door Cooling+ technology, multi-air flow and toughened glass shelves.',
    price: 26990,
    mrp: 37099,
    rating: 4.6,
    reviewCount: 3400,
    stock: 18,
    sku: 'LG-REF-242L-3S',
    thumbnail: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80',
    badge: 'Energy Saver',
    specs: { Capacity: '242 Liters', EnergyRating: '3 Star BEE', Compressor: 'Smart Inverter (10 Year Warranty)', Defrost: 'Frost Free' }
  },
  {
    categoryId: 4,
    subcategoryId: 401,
    brand: 'Samsung',
    name: 'Samsung 236L 3-Star Digital Inverter Frost Free Double Door',
    slug: 'samsung-236l-3-star-digital-inverter-fridge',
    description: 'Digital Inverter technology that automatically adjusts cooling speed across 7 levels, with All-Around Cooling and Easy Slide shelf.',
    price: 25490,
    mrp: 34990,
    rating: 4.5,
    reviewCount: 4100,
    stock: 22,
    sku: 'SAM-REF-236L',
    thumbnail: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '236 Liters', StarRating: '3 Star', Compressor: 'Digital Inverter (20 Year Warranty)', ShelfType: 'Toughened Glass' }
  },
  {
    categoryId: 4,
    subcategoryId: 401,
    brand: 'Whirlpool',
    name: 'Whirlpool 265L 3-Star IntelliFresh Inverter Double Door',
    slug: 'whirlpool-265l-intellifresh-fridge',
    description: 'Powered by 6th Sense IntelliSensor technology, Microblock preventing 99% bacterial growth and Zeolite technology keeping veggies garden fresh for 15 days.',
    price: 27990,
    mrp: 39500,
    rating: 4.4,
    reviewCount: 2200,
    stock: 14,
    sku: 'WHP-REF-265L',
    thumbnail: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '265 Liters', Technology: '6th Sense DeepFreeze', VegetableCrisper: 'Zeolite Tech' }
  },
  {
    categoryId: 4,
    subcategoryId: 401,
    brand: 'Godrej',
    name: 'Godrej 223L 3-Star Nano Shield Inverter Refrigerator',
    slug: 'godrej-223l-nano-shield-fridge',
    description: 'Nano Shield disinfection technology delivering 95%+ surface disinfection, Cool Shower Technology and deep bottom freezer.',
    price: 23990,
    mrp: 31990,
    rating: 4.3,
    reviewCount: 1600,
    stock: 16,
    sku: 'GDJ-REF-223L',
    thumbnail: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '223 Liters', Feature: 'Nano Shield Disinfection', Refrigerant: 'R600a Eco-Friendly' }
  },

  // Washing Machines (402)
  {
    categoryId: 4,
    subcategoryId: 402,
    brand: 'LG',
    name: 'LG 8 Kg 5 Star Inverter AI Direct Drive Front Load Washing Machine',
    slug: 'lg-8kg-ai-dd-front-load-washer',
    description: 'Intelligent AI Direct Drive fabric sensing with Steam Wash eliminating 99.9% allergens, 6 Motion DD wash technology and TurboWash in 59 minutes.',
    price: 36990,
    mrp: 52990,
    rating: 4.7,
    reviewCount: 2900,
    stock: 12,
    sku: 'LG-WM-8KG-AIDD',
    thumbnail: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=600&q=80',
    badge: 'AI Wash 5-Star',
    specs: { Capacity: '8.0 Kg', EnergyRating: '5 Star BEE', Motor: 'Inverter Direct Drive (10 Yr Warranty)', MaxSpinSpeed: '1400 RPM' }
  },
  {
    categoryId: 4,
    subcategoryId: 402,
    brand: 'Bosch',
    name: 'Bosch 7 Kg 5 Star Inverter Touch Control Front Load',
    slug: 'bosch-7kg-inverter-front-load',
    description: 'German engineered EcoSilence Drive motor with Anti-Vibration side panels, SpeedPerfect 65% faster wash and AllergyPlus certified wash cycle.',
    price: 33490,
    mrp: 47990,
    rating: 4.8,
    reviewCount: 1950,
    stock: 15,
    sku: 'BSH-WM-7KG-ECO',
    thumbnail: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '7.0 Kg', Motor: 'EcoSilence Drive Inverter', NoiseLevel: 'Super Silent 49dB', Heater: 'In-built Water Heater' }
  },

  // Air Conditioners (403)
  {
    categoryId: 4,
    subcategoryId: 403,
    brand: 'Daikin',
    name: 'Daikin 1.5 Ton 5 Star Inverter Split AC (Copper, PM 2.5 Filter)',
    slug: 'daikin-1-5-ton-5-star-inverter-ac',
    description: 'Triple Display 5-Star Inverter AC with Neo Swing compressor, PM 2.5 air purification filter, 100% copper condenser and Dew Clean self-cleaning technology.',
    price: 45990,
    mrp: 67200,
    rating: 4.7,
    reviewCount: 2300,
    stock: 10,
    sku: 'DKN-AC-15T-5S',
    thumbnail: 'https://images.unsplash.com/photo-1614633837722-1594892fbdb4?auto=format&fit=crop&w=600&q=80',
    badge: 'Highest Energy Saving',
    specs: { Tonnage: '1.5 Ton', StarRating: '5 Star (ISEER 5.2)', Condenser: '100% Copper', Filter: 'PM 2.5 Anti-Pollution' }
  },
  {
    categoryId: 4,
    subcategoryId: 403,
    brand: 'Voltas',
    name: 'Voltas 1.5 Ton 3 Star Adjustable Inverter Split AC',
    slug: 'voltas-1-5-ton-3-star-inverter-ac',
    description: '4-in-1 Adjustable Mode that runs on 4 different cooling capacities, Superdry humid weather mode and high ambient cooling up to 52°C.',
    price: 32990,
    mrp: 62990,
    rating: 4.4,
    reviewCount: 4600,
    stock: 20,
    sku: 'VLT-AC-15T-3S',
    thumbnail: 'https://images.unsplash.com/photo-1614633837722-1594892fbdb4?auto=format&fit=crop&w=600&q=80',
    specs: { Tonnage: '1.5 Ton', Modes: '4-in-1 Adjustable Cooling', CoolingAt52C: 'Yes' }
  },

  // Water Purifiers & Microwave (408, 404)
  {
    categoryId: 4,
    subcategoryId: 408,
    brand: 'Kent',
    name: 'Kent Grand Plus RO+UV+UF+TDS Control Water Purifier',
    slug: 'kent-grand-plus-ro-water-purifier',
    description: 'Multistage purification with patented TDS Controller retaining essential natural minerals, in-tank UV LED disinfection and 9L storage capacity.',
    price: 15499,
    mrp: 21000,
    rating: 4.6,
    reviewCount: 5200,
    stock: 28,
    sku: 'KNT-GRND-PLS',
    thumbnail: 'https://images.unsplash.com/photo-1546554137-f86b9593a222?auto=format&fit=crop&w=600&q=80',
    badge: 'Mineral RO',
    specs: { Purification: 'RO + UV + UF + TDS Control', Storage: '9 Liters', ProductionRate: '20 Liters/hr' }
  },

  // ==========================================
  // 5. HOME & FURNITURE (Parent ID: 5)
  // ==========================================
  {
    categoryId: 5,
    subcategoryId: 501,
    brand: 'IKEA',
    name: 'IKEA MARKUS High-Back Ergonomic Office Chair',
    slug: 'ikea-markus-ergonomic-office-chair',
    description: 'Iconic mesh back office chair with synchronized tilt mechanism, adjustable height, built-in lumbar support and pressure-sensitive safety castors.',
    price: 14990,
    mrp: 17990,
    rating: 4.7,
    reviewCount: 3100,
    stock: 25,
    sku: 'IKA-MRK-CHR-GRY',
    thumbnail: 'https://images.unsplash.com/photo-1580481077195-c3a82105e3a5?auto=format&fit=crop&w=600&q=80',
    badge: 'Ergonomic Choice',
    specs: { Backrest: 'Breathable Mesh', MaxLoad: '110 kg', Warranty: '10-Year IKEA Guarantee' }
  },
  {
    categoryId: 5,
    subcategoryId: 504,
    brand: 'Sleepwell',
    name: 'Sleepwell Dual Pro Profiled Foam Queen Mattress (78x60x6)',
    slug: 'sleepwell-dual-pro-queen-mattress',
    description: 'Dual-comfort reversible mattress with medium firm on one side and medium soft on the other, Profiled Impression Foam for targeted pressure relief.',
    price: 13999,
    mrp: 18999,
    rating: 4.6,
    reviewCount: 2200,
    stock: 15,
    sku: 'SLP-DUAL-QN-6',
    thumbnail: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    specs: { Size: 'Queen (78 x 60 Inch)', Thickness: '6 Inches', Feel: 'Dual Comfort (Firm & Soft)' }
  },
  {
    categoryId: 5,
    subcategoryId: 503,
    brand: 'Prestige',
    name: 'Prestige Iris Plus 750W Mixer Grinder with 4 Jars',
    slug: 'prestige-iris-plus-750w-mixer-grinder',
    description: 'Heavy duty 750-watt motor equipped with 3 stainless steel grinding jars, 1 transparent juicer jar with extractor and overload protection.',
    price: 3299,
    mrp: 6295,
    rating: 4.4,
    reviewCount: 14200,
    stock: 45,
    sku: 'PRS-IRIS-PLS-750',
    thumbnail: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=600&q=80',
    specs: { Motor: '750 Watts Pure Copper', Jars: '3 Stainless Steel + 1 Juicer Jar', Blades: 'Multi-Utility Stainless Steel' }
  },
  {
    categoryId: 5,
    subcategoryId: 503,
    brand: 'Milton',
    name: 'Milton Thermosteel Flip Lid Insulated 1000ml Bottle',
    slug: 'milton-thermosteel-1000ml-bottle',
    description: 'Double-walled vacuum insulated 18/8 stainless steel flask keeping beverages boiling hot or ice cold for 24 hours with leak-proof flip lid.',
    price: 999,
    mrp: 1290,
    rating: 4.6,
    reviewCount: 8900,
    stock: 80,
    sku: 'MLT-THRM-1000',
    thumbnail: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    specs: { Capacity: '1000 ml', Material: 'SUS 304 Food Grade Stainless Steel', Retention: '24h Hot / 24h Cold' }
  },
  {
    categoryId: 5,
    subcategoryId: 506,
    brand: 'Philips Hue',
    name: 'Philips Hue Smart 9W E27 16 Million Colors LED Bulb',
    slug: 'philips-hue-smart-9w-rgb-bulb',
    description: 'Instant wireless dimming and 16 million colors synchronization with music and movies via Bluetooth and Zigbee, Alexa and Google Assistant ready.',
    price: 2499,
    mrp: 3499,
    rating: 4.7,
    reviewCount: 1800,
    stock: 50,
    sku: 'PH-HUE-9W-RGB',
    thumbnail: 'https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=600&q=80',
    badge: '16M Colors',
    specs: { Wattage: '9W (806 Lumens)', CapBase: 'E27 Screw Base', VoiceControl: 'Alexa, Google Assistant, Apple HomeKit' }
  },

  // ==========================================
  // 6. BEAUTY & GROOMING (Parent ID: 6)
  // ==========================================
  {
    categoryId: 6,
    subcategoryId: 601,
    brand: 'Minimalist',
    name: 'Minimalist 10% Niacinamide Face Serum with Zinc (30ml)',
    slug: 'minimalist-10-niacinamide-serum',
    description: 'Pore refining and oil control serum formulated with EU sourced pure Niacinamide (Vitamin B3) and Zinc PCA to reduce acne spots and improve skin barrier.',
    price: 569,
    mrp: 599,
    rating: 4.6,
    reviewCount: 18900,
    stock: 120,
    sku: 'MIN-NIAC-10-30ML',
    thumbnail: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
    badge: 'Top Serum',
    specs: { Volume: '30 ml', ActiveIngredient: '10% Niacinamide + 1% Zinc PCA', SkinType: 'All Skin Types (Acne Prone)', FragranceFree: 'Yes' }
  },
  {
    categoryId: 6,
    subcategoryId: 601,
    brand: 'Forest Essentials',
    name: 'Forest Essentials Delicate Facial Cleanser Kashmiri Saffron & Neem',
    slug: 'forest-essentials-facial-cleanser-saffron-neem',
    description: 'Traditional Ayurvedic gentle facial cleanser enriched with organic Kashmiri saffron, neem bark and sweet almond oil to purify and balance skin moisture.',
    price: 1575,
    mrp: 1750,
    rating: 4.8,
    reviewCount: 2300,
    stock: 35,
    sku: 'FE-CLN-SAFF-200ML',
    thumbnail: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    specs: { Volume: '200 ml', Type: 'Ayurvedic Facial Cleanser', KeyIngredients: 'Kashmiri Saffron, Neem, Rose Water' }
  },
  {
    categoryId: 6,
    subcategoryId: 602,
    brand: "L'Oreal Paris",
    name: "L'Oreal Paris Total Repair 5 Repairing Shampoo (650ml)",
    slug: 'loreal-paris-total-repair-5-shampoo-650ml',
    description: 'Formulated with Keratin XS complex to combat 5 signs of hair damage: hair fall, dryness, roughness, dullness and split ends.',
    price: 499,
    mrp: 749,
    rating: 4.5,
    reviewCount: 24500,
    stock: 90,
    sku: 'LOR-TR5-SHM-650',
    thumbnail: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80',
    specs: { Volume: '650 ml', Formula: 'Keratin XS Complex', HairType: 'Damaged & Weak Hair' }
  },
  {
    categoryId: 6,
    subcategoryId: 603,
    brand: 'Maybelline',
    name: 'Maybelline New York Super Stay Matte Ink Liquid Lipstick',
    slug: 'maybelline-super-stay-matte-ink-ruler',
    description: 'Transfer-proof, waterproof matte liquid lipstick with intense pigment delivering up to 16 hours of flawless, smudge-resistant wear.',
    price: 549,
    mrp: 699,
    rating: 4.6,
    reviewCount: 16800,
    stock: 80,
    sku: 'MAY-SS-MATTE-RUL',
    thumbnail: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80',
    specs: { Finish: 'Intense Matte', WearTime: 'Up to 16 Hours', Applicator: 'Precision Arrow Tip' }
  },
  {
    categoryId: 6,
    subcategoryId: 606,
    brand: 'Philips Grooming',
    name: 'Philips Series 3000 Self-Sharpening Beard Trimmer (Lift & Trim)',
    slug: 'philips-bt3231-beard-trimmer',
    description: 'Fast and even trim with Lift & Trim system, titanium coated self-sharpening blades, 20 length settings (0.5mm - 10mm) and 60 mins cordless runtime.',
    price: 1899,
    mrp: 2395,
    rating: 4.6,
    reviewCount: 31000,
    stock: 65,
    sku: 'PH-BT3231-TRM',
    thumbnail: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80',
    badge: '60 Min Runtime',
    specs: { Blades: 'Titanium Coated Self-Sharpening', LengthSettings: '20 Lock-in Settings (0.5 - 10mm)', BatteryLife: '60 Minutes (USB Charging)' }
  },

  // ==========================================
  // 7. SPORTS & FITNESS (Parent ID: 7)
  // ==========================================
  {
    categoryId: 7,
    subcategoryId: 701,
    brand: 'Decathlon',
    name: 'Decathlon Domyos Hex Rubber Dumbbells Pair (10kg Each)',
    slug: 'decathlon-domyos-hex-dumbbells-10kg-pair',
    description: 'Heavy-duty cast iron hexagonal dumbbells coated in thick floor-protecting rubber with ergonomic chrome contoured knurled handles.',
    price: 3499,
    mrp: 4999,
    rating: 4.8,
    reviewCount: 4200,
    stock: 30,
    sku: 'DEC-HEX-10KG-PR',
    thumbnail: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&w=600&q=80',
    badge: 'Pro Cast Iron',
    specs: { Weight: '10kg x 2 (Total 20kg)', Material: 'Cast Iron with Rubber Coating', Grip: 'Knurled Chrome Ergo Handle' }
  },
  {
    categoryId: 7,
    subcategoryId: 705,
    brand: 'Yonex',
    name: 'Yonex Nanoray Light 18i Carbon Graphite Badminton Racquet',
    slug: 'yonex-nanoray-light-18i-racquet',
    description: 'Ultra-lightweight 77g racquet with high-modulus carbon graphite frame, isometric head shape and high-tension stringing capacity up to 30 lbs.',
    price: 2190,
    mrp: 3490,
    rating: 4.7,
    reviewCount: 8900,
    stock: 45,
    sku: 'YNX-NR-LT-18I',
    thumbnail: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=600&q=80',
    badge: '77g Lightweight',
    specs: { Weight: '5U (77g)', MaxTension: '30 lbs', Frame: 'Full Carbon Graphite' }
  },
  {
    categoryId: 7,
    subcategoryId: 703,
    brand: 'SG',
    name: 'SG Player Grade English Willow Cricket Bat',
    slug: 'sg-english-willow-cricket-bat-full-size',
    description: 'Handcrafted from selected Grade 3 English willow with thick contoured edges, large sweet spot, Sarawak cane handle and chevron grip.',
    price: 8999,
    mrp: 12500,
    rating: 4.7,
    reviewCount: 1200,
    stock: 20,
    sku: 'SG-ENG-WIL-BAT',
    thumbnail: 'https://images.unsplash.com/photo-1531415074868-036b10554f31?auto=format&fit=crop&w=600&q=80',
    specs: { Willow: 'Selected English Willow Grade 3', Size: 'Full Size Men (SH)', Handle: 'Multi-Piece Sarawak Cane' }
  },
  {
    categoryId: 7,
    subcategoryId: 704,
    brand: 'Nivia',
    name: 'Nivia Storm Thermo Bonded Match Football (Size 5)',
    slug: 'nivia-storm-match-football-size-5',
    description: 'Seamless thermo-bonded official match ball featuring high-abrasion PU micro-texture, reinforced butyl bladder and FIFA quality standards.',
    price: 1199,
    mrp: 1799,
    rating: 4.5,
    reviewCount: 6100,
    stock: 50,
    sku: 'NIV-STRM-FB-S5',
    thumbnail: 'https://images.unsplash.com/photo-1614632537197-38a17061c2bd?auto=format&fit=crop&w=600&q=80',
    specs: { Size: 'Size 5 (Official Match)', Construction: 'Seamless Thermo-Bonded 32-Panel', Bladder: 'Air Lock Butyl' }
  },
  {
    categoryId: 7,
    subcategoryId: 706,
    brand: 'Firefox',
    name: 'Firefox Bikes Grunge 27.5T 21-Speed Mountain Bike',
    slug: 'firefox-grunge-27-5t-mountain-bike',
    description: 'Rugged alloy hardtail mountain bicycle featuring Shimano Tourney 21-speed gears, front suspension fork with 80mm travel and dual mechanical disc brakes.',
    price: 16999,
    mrp: 22500,
    rating: 4.6,
    reviewCount: 780,
    stock: 12,
    sku: 'FFX-GRNG-275T',
    thumbnail: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
    badge: 'Shimano 21-Speed',
    specs: { WheelSize: '27.5 Inches', Gears: 'Shimano 21-Speed Tourney', Brakes: 'Dual Mechanical Disc Brakes', Frame: 'Steel Hardtail' }
  },

  // ==========================================
  // 8. BOOKS (Parent ID: 8)
  // ==========================================
  {
    categoryId: 8,
    subcategoryId: 808,
    brand: 'Penguin',
    name: 'Atomic Habits by James Clear (Hardcover Edition)',
    slug: 'atomic-habits-james-clear',
    description: 'An easy & proven way to build good habits and break bad ones. The definitive international #1 bestseller on behavioral psychology and self improvement.',
    price: 549,
    mrp: 799,
    rating: 4.9,
    reviewCount: 45000,
    stock: 100,
    sku: 'BK-ATOM-HAB-HC',
    thumbnail: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    badge: '#1 Global Bestseller',
    specs: { Author: 'James Clear', Publisher: 'Penguin Random House', ISBN: '978-0735211292', Format: 'Hardcover', Pages: '320', Language: 'English' }
  },
  {
    categoryId: 8,
    subcategoryId: 807,
    brand: 'HarperCollins',
    name: 'The Psychology of Money by Morgan Housel',
    slug: 'psychology-of-money-morgan-housel',
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn’t necessarily about what you know. It’s about how you behave.',
    price: 349,
    mrp: 499,
    rating: 4.8,
    reviewCount: 38000,
    stock: 80,
    sku: 'BK-PSYC-MON-PB',
    thumbnail: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    specs: { Author: 'Morgan Housel', Publisher: 'HarperCollins India', ISBN: '978-9390166268', Format: 'Paperback', Pages: '256', Language: 'English' }
  },
  {
    categoryId: 8,
    subcategoryId: 801,
    brand: 'HarperCollins',
    name: 'The Alchemist by Paulo Coelho (Deluxe Edition)',
    slug: 'the-alchemist-paulo-coelho',
    description: 'A magical story about following your dreams, listening to your heart and recognizing opportunities along life’s journey.',
    price: 299,
    mrp: 399,
    rating: 4.7,
    reviewCount: 52000,
    stock: 75,
    sku: 'BK-ALCH-PC-DLX',
    thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    specs: { Author: 'Paulo Coelho', Publisher: 'HarperCollins', ISBN: '978-8172234980', Format: 'Paperback', Pages: '208' }
  },
  {
    categoryId: 8,
    subcategoryId: 804,
    brand: 'McGraw Hill',
    name: 'Quantitative Aptitude for CAT by Arun Sharma (10th Edition)',
    slug: 'quantitative-aptitude-cat-arun-sharma',
    description: 'The undisputed benchmark comprehensive textbook for cracking Quantitative Aptitude in CAT, XAT, IIFT, and premier management competitive exams.',
    price: 849,
    mrp: 1095,
    rating: 4.7,
    reviewCount: 6500,
    stock: 50,
    sku: 'BK-CAT-QA-ARUN',
    thumbnail: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80',
    badge: 'CAT Benchmark',
    specs: { Author: 'Arun Sharma', Publisher: 'McGraw Hill Education', ISBN: '978-9355322968', Format: 'Paperback', Pages: '960' }
  },

  // ==========================================
  // 9. TOYS & GAMES (Parent ID: 9)
  // ==========================================
  {
    categoryId: 9,
    subcategoryId: 901,
    brand: 'LEGO',
    name: 'LEGO Technic Bugatti Bolide Racing Car Building Set 42151',
    slug: 'lego-technic-bugatti-bolide-42151',
    description: 'Authentic 905-piece build featuring a working W16 engine with moving pistons, functional steering, scissor doors and iconic yellow/black race livery.',
    price: 4999,
    mrp: 5999,
    rating: 4.9,
    reviewCount: 3800,
    stock: 25,
    sku: 'LGO-TECH-42151',
    thumbnail: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80',
    badge: 'LEGO Technic',
    specs: { Pieces: '905 Pieces', AgeGroup: '9 Years & Above', Dimensions: '31cm L x 14cm W x 8cm H' }
  },
  {
    categoryId: 9,
    subcategoryId: 904,
    brand: 'Hasbro',
    name: 'Hasbro Gaming Monopoly Classic Fast-Dealing Property Board Game',
    slug: 'hasbro-monopoly-classic-board-game',
    description: 'The world’s favorite family property trading game with classic metal tokens, houses, hotels, chance cards and community chest cards.',
    price: 1099,
    mrp: 1499,
    rating: 4.7,
    reviewCount: 18500,
    stock: 60,
    sku: 'HSB-MONOP-CLS',
    thumbnail: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80',
    specs: { Players: '2 to 6 Players', AgeGroup: '8 Years & Above', Included: 'Gameboard, 8 Tokens, 28 Title Deed Cards, Money Pack' }
  },
  {
    categoryId: 9,
    subcategoryId: 902,
    brand: 'Hasbro',
    name: 'Hasbro Marvel Legends Series Spider-Man 6-inch Action Figure',
    slug: 'hasbro-marvel-legends-spider-man-6-inch',
    description: 'Premium collectible 6-inch scale classic comics Spider-Man action figure featuring over 20 points of articulation and alternate web hands.',
    price: 2199,
    mrp: 2799,
    rating: 4.8,
    reviewCount: 2200,
    stock: 35,
    sku: 'HSB-MVL-SPDR-6IN',
    thumbnail: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=600&q=80',
    specs: { Character: 'Spider-Man', Scale: '6-Inch (15 cm)', Articulation: 'Over 20 Points' }
  },
  {
    categoryId: 9,
    subcategoryId: 907,
    brand: 'Nerf',
    name: 'Nerf Ultra One Motorized High-Capacity Dart Blaster',
    slug: 'nerf-ultra-one-motorized-blaster',
    description: 'High-capacity 25-dart motorized drum blaster firing groundbreaking Nerf Ultra darts up to 120 feet (36 meters) with extreme distance and accuracy.',
    price: 3499,
    mrp: 4999,
    rating: 4.6,
    reviewCount: 4100,
    stock: 30,
    sku: 'NRF-ULTRA-ONE',
    thumbnail: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=600&q=80',
    badge: 'Fires Up to 120ft',
    specs: { FiringMechanism: 'Motorized Electric', Capacity: '25-Dart Drum', Range: 'Up to 36 meters' }
  },

  // ==========================================
  // 10. GROCERY & DAILY ESSENTIALS (Parent ID: 10)
  // ==========================================
  {
    categoryId: 10,
    subcategoryId: 1004,
    brand: 'Daawat',
    name: 'Daawat Rozana Gold Basmati Rice (5kg Bag)',
    slug: 'daawat-rozana-gold-basmati-rice-5kg',
    description: 'Long grain, rich aromatic aged basmati rice perfect for daily delicious biryanis, pulao, fried rice and steamed rice.',
    price: 499,
    mrp: 650,
    rating: 4.5,
    reviewCount: 16500,
    stock: 150,
    sku: 'DWT-RZNA-GLD-5KG',
    thumbnail: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    badge: 'Aged Basmati',
    specs: { Weight: '5 kg', GrainType: 'Long Grain Basmati', ShelfLife: '24 Months', DietType: '100% Vegetarian' }
  },
  {
    categoryId: 10,
    subcategoryId: 1004,
    brand: 'Fortune',
    name: 'Fortune Sunlite Refined Sunflower Oil (5 Liter Can)',
    slug: 'fortune-sunlite-sunflower-oil-5l',
    description: 'Enriched with Vitamin A and Vitamin D, light and easy to digest healthy cooking oil with high smoke point for crispy guilt-free frying.',
    price: 699,
    mrp: 950,
    rating: 4.6,
    reviewCount: 22000,
    stock: 120,
    sku: 'FRT-SUN-OIL-5L',
    thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    specs: { Volume: '5 Liters', Type: 'Refined Sunflower Oil', Nutrients: 'Fortified with Vitamin A & D' }
  },
  {
    categoryId: 10,
    subcategoryId: 1003,
    brand: 'Nescafe',
    name: 'Nescafe Classic 100% Pure Instant Coffee Glass Jar (200g)',
    slug: 'nescafe-classic-instant-coffee-200g',
    description: 'Distinctive rich dark roast coffee aroma with bold refreshing flavor made from 100% carefully selected Robusta and Arabica coffee beans.',
    price: 599,
    mrp: 690,
    rating: 4.7,
    reviewCount: 31000,
    stock: 180,
    sku: 'NES-CLS-COF-200G',
    thumbnail: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80',
    specs: { Weight: '200g', RoastType: 'Medium-Dark Roast', Caffeine: 'Caffeinated' }
  },
  {
    categoryId: 10,
    subcategoryId: 1006,
    brand: "Kellogg's",
    name: "Kellogg's Corn Flakes Original with Real Almond & Honey (1kg)",
    slug: 'kelloggs-corn-flakes-almond-honey-1kg',
    description: 'Crisp golden toasted corn flakes loaded with crunchy sliced almonds and pure honey. Packed with 7 essential vitamins and iron for an energetic breakfast.',
    price: 489,
    mrp: 595,
    rating: 4.5,
    reviewCount: 14200,
    stock: 95,
    sku: 'KEL-CRN-ALM-1KG',
    thumbnail: 'https://images.unsplash.com/photo-1521483451569-e33803c0330c?auto=format&fit=crop&w=600&q=80',
    specs: { Weight: '1 kg', Ingredients: 'Corn Flakes, Honey, Sliced Almonds', Fortified: 'B-Group Vitamins & Iron' }
  },
  {
    categoryId: 10,
    subcategoryId: 1008,
    brand: 'Surf Excel',
    name: 'Surf Excel Matic Front Load Liquid Detergent (2 Liter Pouch)',
    slug: 'surf-excel-matic-front-load-liquid-2l',
    description: 'Advanced stain removal technology that dissolves completely in water, penetrates fibers quickly and leaves zero residue in washing machines.',
    price: 435,
    mrp: 530,
    rating: 4.8,
    reviewCount: 29000,
    stock: 110,
    sku: 'SRF-MAT-FRNT-2L',
    thumbnail: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
    specs: { Volume: '2 Liters', MachineCompatibility: 'Front Load Washing Machines', Formulation: 'Concentrated Liquid' }
  }
];

module.exports = { additionalProducts };
